-- Table for storing multi-label annotation results
-- This table stores the tags generated by the LLM for a specific feedback entry
CREATE TABLE IF NOT EXISTS tags (
    id SERIAL PRIMARY KEY,

    -- Foreign Key referencing the feedbacks table
    -- If a feedback entry is deleted, its tags are also deleted (CASCADE)
    feedback_id INT REFERENCES feedbacks(id) ON DELETE CASCADE,

    -- The array of tags (e.g., ['UI', 'Bug'])
    tags TEXT[],

    -- Metadata to track which model generated these tags
    model_name VARCHAR(50),

    created_at TIMESTAMP DEFAULT NOW()
);

-- GIN Index for efficient array searching
-- Allows queries like: SELECT * FROM tags WHERE 'Bug' = ANY(tags);
CREATE INDEX IF NOT EXISTS idx_tags_tags ON tags USING GIN(tags);

-- Index for quickly finding tags for a specific feedback
CREATE INDEX IF NOT EXISTS idx_tags_feedback_id ON tags(feedback_id);
